### ISSUE TITLE
No support for Integer keyed options

### ISSUE THREAD

**Issue by aalyusuf** [Silvanite/novafieldcheckboxes#1]
When you have an array of options :
```
[
        0 => 'Sunday',
        1 => 'Monday',
        2 => 'Tuesday',
]
```
Once you save It , It will be stored as ["0","1"..] 

Cause of this is the use of explode function , it will turn 1,2,3 into an array of strings instead of integers

**Comment by m2de** [comment]
Thanks @aalyusuf for the report. I need to open an issue on the nova repo as I'm unsure why it is returning the options as String in the first place. I could not work out why it was happening, hence the *backup* explode function.

I will try and come up with a temporary solution though.
