### ISSUE TITLE
What is the best way to convert the db field back to an array?

### ISSUE THREAD

**Issue by 949mac** [Silvanite/novafieldcheckboxes#14]
Here you can see how the strings are saved in the database table:

![image](https://user-images.githubusercontent.com/23151962/49962884-54d71c80-fecb-11e8-8cc1-f0936139e03f.png)

When fetching them, via `$table->email_recipient`, they are strings and not arrays. I do have the type casting set and I don't receive any errors in Nova when storing, updating, or showing.

**Comment by 949mac** [comment]
I found the issue. It had a statement using DB rather than the model. Sorry for the confusion!

**Comment by m2de** [comment]
No problem @949mac . Glad you sorted it, thanks for the update.
