### ISSUE TITLE
Styling of the container

### ISSUE THREAD

**Issue by ragingdave** [Silvanite/novafieldcheckboxes#2]
I was using this inside of https://github.com/64robots/nova-json and noticed that the checkboxes are super compacted, and also cut off a bit. Any chance you can add styling to this field so that we can make the checkboxes full width rather than keeping them only half width? 

For refernce:
https://github.com/64robots/nova-json/issues/1

**Comment by m2de** [comment]
Hi @ragingdave . Thanks for raising this. I noticed this too (on smaller monitors the display of multiple columns is not right). Will review as soon as possible.

**Comment by m2de** [comment]
Hi @ragingdave . I just pushed a minor update 1.0.5 to avoid unwanted line-breaks. I have not used the R64 fields, could you please let me know if the display is still broken and post a screenshot if it is? Thank you.

**Comment by ragingdave** [comment]
That does eliminate the line breaks, but seems to cut off text for long checkbox labels. Although my use case has probably half the size of the screen available due to the 64robots/nova-json usage but still.

![screen shot 2018-09-12 at 9 36 16 am](https://user-images.githubusercontent.com/1168344/45428632-a1fae680-b66f-11e8-91f6-082e9f9aefec.png)

**Comment by m2de** [comment]
Thanks @ragingdave ... will look at making the column count responsive whilst maintaining the correct ordering.

**Comment by m2de** [comment]
Hi @ragingdave , please could you confirm if you are happy with the implementation now and I can close this issue or do you still have layout problems? Cheers.

**Comment by ragingdave** [comment]
It no longer cuts off and displays well. There is another super minor display issue but I'm not sure if the cause is specifically this package or the interaction between the wrapping component, so I'll hold off on that for now. But otherwise all Good!
