### ISSUE TITLE
padding needs to be margin

### ISSUE THREAD

**Issue by mziraki** [Silvanite/novafieldcheckboxes#26]
https://github.com/Silvanite/novafieldcheckboxes/blob/cfe8da42eb1fec013db437222921d1a5c6dec12c/resources/js/components/FormField.vue#L17

in new nova version (2.8.0) pr-2 does not create the space between label and checkbox! but mr-2 does the trick

**Comment by mziraki** [comment]
@m2de it affects your nova ACL package

**Comment by m2de** [comment]
Thanks @mziraki for the heads up. What an annoying change in 2.8, will try and patch that today.

**Comment by m2de** [comment]
Fixed in 1.2.1 e0fc0b0a356d4eb7a43261f36bc8a016ae6dbdd7
