### ISSUE TITLE
Regression: display bug has returned

### ISSUE THREAD

**Issue by ragingdave** [Silvanite/novafieldcheckboxes#30]
#2 seems to have re-occurred again as the checkboxes are breaking over the columns again:

![Screen Shot 2019-12-03 at 9 40 42 AM](https://user-images.githubusercontent.com/1168344/70060677-007fed80-15b1-11ea-97a8-093885ec76c7.png)

Note the cutting off of the last checkbox in a column where there are 2 columns. The top one was just my screenshot and not a display issue.

Additionally, I noticed that there is now some spacing issues between the checkbox and it's label that wasn't there before as well.

**Comment by ragingdave** [comment]
Any update on this?

**Comment by m2de** [comment]
Pretty sure this has been resolved by now in the latest version. Please let me know if it's still an issue and will re-open / resolve. Thanks @ragingdave .

**Comment by ragingdave** [comment]
Can confirm that on the latest version (1.2.1). Perhaps different from the original issue could be that the cut off is only happening where there are an odd number of checkboxes to display.
