### ISSUE TITLE
Write Checkbox Data to DB

### ISSUE THREAD

**Issue by randyrankin** [Silvanite/novafieldcheckboxes#7]
I have the following tables:

**users**

- id
- name

**meetings**

- id
- topic

**meeting_user**

- meeting_id
- user_id

I have also created the following in the User and Meeting models:

```
class User extends Model
{
    /**
     * The meetings that belong to the user
     */
    public function meetings()
    {
        return $this->belongsToMany('App\Meeting');
    }
}
```
and 

```

class Meeting extends Model
{
    /**
     * The users that belong to the meeting
     */
    public function users()
    {
        return $this->belongsToMany('App\User');
    }
}
```
In my Nova Meeting resource, I have the following:

```
return [
...
Checkboxes::make('Users')->options(collect(\App\User::all())
                ->mapWithKeys(function ($user) {
                    return [
                        $user->id => $user->name,
                    ];
                })
                ->sort()
                ->toArray()),
...
]
```
This renders user checkboxes on the meetings form (beautifully, btw), but I don't understand how to write the data to the meeting_user table. Can you guide me?

**Comment by randyrankin** [comment]
**Update** - I stripped out all the stuff in my previous comment above and created a TEXT field in the meetings table called participants. In the nova Meeting resources, I have the following :

```
Checkboxes::make('Participants')->options(collect(\App\User::all())
                ->mapWithKeys(function ($user) {
                    return [
                        $user->id => $user->name,
                    ];
                })
                ->sort()
                ->toArray()
),
```
In my Meeting model, if I add:

```
protected $casts = [
        'participants' => 'array',
    ];
```
I can create meeting model and the id's of the selected user are written to the participants field as, for example,  `[1,3,7]` but the indicators on the resource index and view are all red.  If I remove  `$casts ...`, they green up as appropriate, but in order to edit (or create a new meeting), I must add `$casts` back to the Meeting model. 

It is also interesting to note that when I remove `$casts ...`, the array is just added to in the table, so I end up with, for example, `[1,3,7,1,3,7,8]. 

I think I am much closer, but could use a bit of guidance. Am I just going about this all wrong?

**Comment by m2de** [comment]
Hi @randyrankin . Thanks for your feedback. Your revised approach is definitely correct and you should be casting to array as you are doing. 

One possible issue to investigate is to check if the user ID key passed into the options is passed in as a string, rather than an integer. E.g. The value stored in the database is an integer, but the value in the `->options()` is a numeric string.

**Comment by wa7eedem** [comment]
Hi all , 
I have a smiler structure , and its the same thing , 
if I enable the  `casting to array` I get : `1,2,3` in the database

but in the edit form , the Checkboxes is not `checked` .

I had to edit the file `Checkboxes.php` for testing and disable :  `castValueToType`

to get the data as : `["11","4"]`

my field is : 

```
Checkboxes::make('apps')->options(
            collect(Apps::get())
            ->mapWithKeys(function($app) {
                return [
                    $app->id => $app->name,
                ];
            })
            ->sort()
            ->toArray()
        )
```

what should I do to keep the values in the database as :  `["11","4"]`?

thank you .

**Comment by randyrankin** [comment]
@wa7eedem Try creating your `apps` field as type text in your migration (example `$table->text('app');`) and cast as `protected $casts = [ 'app' => 'array',];`  in your model

**Comment by wa7eedem** [comment]
@randyrankin  yup , its already a `text` field and I do have the : 

```
$casts      = [
        'apps' => 'array',
    ];
```

and its the same issue .

**Comment by wa7eedem** [comment]
yes , actually after doing the `text field` and add the `cast to array` ,
the only way to make it works for me is be disabling the `castValueToType`

I saw @m2de added this to [fix some issues](https://github.com/Silvanite/novafieldcheckboxes/issues/1) , and its cause me another one , I think its depend on how we will handling the stored data 
as `[1,2,3]` or `["1","2","3"]`


@m2de could this be an optional ? like : 

`Checkboxes::make('apps')->options($apps)->withCastValueToType()`

**Comment by m2de** [comment]
Yeah totally, been thinking about making it configurable, seems like a good
idea if there is a valid use case for it.

Not sure when I will have time to implement but feel free to PR this as a
feature ;)

Cheers!

**Comment by wa7eedem** [comment]
I will give it a try :)

**Comment by m2de** [comment]
P.s i think an option like ->withoutTypeCasting() would be better to avoid
a breaking change.

**Comment by m2de** [comment]
Revolved with #10

**Comment by niladam** [comment]
Is there anyway we could make this work with a BelongsToMany relationship ?
