### ISSUE TITLE
Spatie Permissions

### ISSUE THREAD

**Issue by johnpaulmedina** [Silvanite/novafieldcheckboxes#9]
How do you implement this with permissions?

`Checkboxes::make('Roles')->options(\App\Models\Role::all()->pluck('name','id')->toArray())->hideFromIndex(),
`
But they do not check if they are part of this role

**Comment by m2de** [comment]
Hi. Thanks for your query. The options array needs to be key value pairs, e.g. `[1 => 'Role']`, I think your code returns `['id' => 1, 'name' => 'Role']? Hope that helps.

**Comment by johnpaulmedina** [comment]
Actually that returns ['Name'=>'ID'] key value pairs. It doesn't automatically check based on the relationship.

**Comment by m2de** [comment]
Hi @johnpaulmedina . Thanks for the update. Please could you clarify if you still have an issue or have you resolved this?

**Comment by mortezarajabi** [comment]
I use this package for attaching roles to a user like this. (in case if you are not going to modify the package source)

In User resource:
```
Checkboxes::make(__('Roles'), 'roles_field')
    ->options(\Spatie\Permission\Models\Role::pluck('name', 'id')->toArray())
    ->withoutTypeCasting()
    ->hideFromIndex()
    ->hideWhenCreating(),
```

In my User model:

```
public static function boot()
{
    parent::boot();

    static::updating(function ($model) {
        $model->syncRoles($model->roles_field);
        unset($model->roles_field);
    });
}

public function getRolesFieldAttribute($value)
{        
    // cast array elements to string, because checkboxes won't be checked with integer values
    return array_map('strval', $this->roles()->pluck('id')->toArray());
}
```

I hope to have support for BelongsToMany and MorphToMany soon!

**Comment by mortezarajabi** [comment]
If you want to attach roles to user without modifying the package you can:

In User resource

```
Checkboxes::make(__('Roles'), 'roles')
    ->options(\Spatie\Permission\Models\Role::orderBy('name')->pluck('name', 'id')->toArray())
    ->withoutTypeCasting()
    ->hideFromIndex() 
```

in User model

```
public function getRolesAttribute($value)
{        
    // cast array elements to string.
    // check boxes won't be checked with integer value

    return array_map('strval', $this->roles()->pluck('id')->toArray());
}

public function setRolesAttribute($value)
{        
    return $this->syncRoles($value);
}
```

I hope to have support for BelongsToMany and MorphToMany as well.

**Comment by HenocKA** [comment]
> If you want to attach roles to user without modifying the package you can:
> 
> In User resource
> 
> ```
> Checkboxes::make(__('Roles'), 'roles')
>     ->options(\Spatie\Permission\Models\Role::orderBy('name')->pluck('name', 'id')->toArray())
>     ->withoutTypeCasting()
>     ->hideFromIndex() 
> ```
> in User model
> 
> ```
> public function getRolesAttribute($value)
> {        
>     // cast array elements to string.
>     // check boxes won't be checked with integer value
> 
>     return array_map('strval', $this->roles()->pluck('id')->toArray());
> }
> 
> public function setRolesAttribute($value)
> {        
>     return $this->syncRoles($value);
> }
> ```
> I hope to have support for BelongsToMany and MorphToMany as well.

Awesome !!! This comment should be in the readme !

**Comment by shazibrazzaq** [comment]
it works with belongsToMany i tested.
